config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get    'about' , to: 'static_pages#about'
  get    'userlist' , to: 'static_pages#userlist'
  resources :users do
    member do
      get 'followings','followers'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :profile_name, presence: true, length: { maximum: 100 }, on: :update
  validates :area, presence: true, length: { maximum: 50 }, on: :update
  validates :age, numericality: { only_integer: true , greater_than_or_equal_to: 0 , less_than_or_equal_to: 200 } , presence: true, on: :update 

  has_secure_password

  has_many :microposts
  
  
   
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  #following_relationshipsのforeign_keyのfollower_idにuserのidが入るので、user.following_relationshipsによって、
  #userがフォローしている場合のRelationshipを取得することができます。
  
  #following_usersでは、has_many 〜 throughという文を使っています。throughには、following_relationshipsが指定されていて、
  #following_relationshipsを経由してデータを取得することを意味しています。
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  
  #userがフォローしている人は、following_relationshipsのfollowed_idに一致するユーザーになるので、sourceとしてfollowedを指定しています。
  has_many :following_users, through: :following_relationships, source: :followed
  
  

  #follower_relationshipsのforeign_keyのfollowed_idにuserのidが入るので、user.follower_relationshipsによって、userがフォローされている場合のRelationshipを取得することができます。
  #follower_usersの、has_many 〜 throughのthroughには、follower_relationshipsが指定されていて、上の図のように、follower_relationshipsを経由してデータを取得することを意味しています。
  #userをフォローしている人は、follower_relationshipsのfollower_idに一致するユーザーになるので、sourceとしてfollowerを指定しています。
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  paginates_per 2  # 1ページあたり2項目表示

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
       @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc) # この行を追加
       render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost = current_user.microposts.find_by(id: params[:id])
    return redirect_to root_url if @micropost.nil?
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  def micropost_params
    params.require(:micropost).permit(:content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :logged_in_user

  def create
    #createメソッドでは、フォローする他のユーザーのIDをパラメータとして受け取り、
    #見つかったユーザーを引数としてUserモデルのfollowメソッドを実行します。
    
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
  end

  def destroy
    #destroyメソッドは、現在のユーザーのfollowing_relationshipsを検索して他のユーザーをフォローしている場合は、
    #そのユーザーを引数としてUserのunfollowメソッドを実行します。

    @user = current_user.following_relationships.find(params[:id]).followed
    current_user.unfollow(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
   def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
#    @micropost = current_user.microposts.build if logged_in?
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
    end
  end
  def about
  end
  
  def userlist
      @users = User.all
      @users = User.page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def followings
    @title = "followings"
    @user = User.find(params[:id])
    @users = @user.following_users
    @follows = @users.page(params[:page])
    
  end


  def followers
    @title = "followers"
    @user = User.find(params[:id])
    @users = @user.follower_users
    @follows = @users.page(params[:page])
    render 'followings'
  end


  def show # 追加
   @user = User.find(params[:id])
   @microposts = @user.microposts
  end
  
  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end

    
  end
  

  def create
    
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :age , :profile_name ,:area)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", userlist_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>     <!--編集画面へのリンク-->
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
   <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>

</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/relationships/estroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<h1>About</h1>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div>
      <h3>Micropst Feed</h3>
        <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Microposts</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/static_pages/userlist.html.erb
<h1>UserList</h1>


<!-- 追加箇所開始 -->
<%= page_entries_info @users %>
<!-- 追加箇所終了 -->
<% @users.each do |user| %>
  <li>
    <%= link_to gravatar_for(user, size: 50), user %>
    <span class="user"><%= link_to user.name, user %></span><br>
    <span class="user"><%= link_to user.email, user %></span><br>
     <span class="timestamp">
      Posted <%= time_ago_in_words(user.created_at) %> ago.
    </span><br>
  </li>
  
  
<% end %>


<!-- 追加箇所開始 -->
<%= paginate @users %>
<!-- 追加箇所終了 -->

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default col-sm-10 form-horizontal" >
  <div class="panel-heading">ProFile Edit</div>
  <div class="form-horizontal" role="form">
  <%= form_for(@user) do |f| %>
  
      <% if @user.errors.present? %>
        <div class="alert alert-danger">
          <%= alert %>
          <ul>
            <% @user.errors.full_messages.each do |full_message| %>
              <li>
                <%= full_message %>
              </li>
            <% end %> 
          </ul>
        </div>
      <% end %>
      <br>
      <div class="form-group">
          <label for="user_name" class="col-sm-2 control-label">name：</label>
          <div class="col-sm-4">
            <%= f.text_field :name, :class => "form-control", :placeholder => "名前を入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_email" class="col-sm-2 control-label">email：</label>
          <div class="col-sm-4">
            <%= f.text_field :email, :class => "form-control", :placeholder => "メールアドレスを入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_password" class="col-sm-2 control-label">password：</label>
          <div class="col-sm-4">  
            <%= f.password_field :password, :class => "form-control", :placeholder => "パスワードを入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_password_confirmation" class="col-sm-2 control-label">Confirmation：</label>
          <div class="col-sm-4">
            <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "パスワード再度入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_age" class="col-sm-2 control-label">Age：</label>
          <div class="col-sm-2">
            <%= f.number_field :age, :class => "form-control", :placeholder => "年齢" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_profile_name" class="col-sm-2 control-label">Profile：</label>
          <div class="col-sm-4">
            <%= f.text_field :profile_name, :class => "form-control", :placeholder => "プロファイル" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_area" class="col-sm-2 control-label">Area：</label>
          <div class="col-sm-4">
            <%= f.text_field :area, :class => "form-control", :placeholder => "地域" %>
          </div>    
      </div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-2"> 
              <%= f.submit class: "btn btn-sm btn-primary" %> 
          </div>
      </div>
   <% end %>
</div>


</div>

app/views/users/followings.html.erb
<h1><%= @title %></h1>

<!-- 追加箇所開始 -->
<%= page_entries_info @follows %>
<!-- 追加箇所終了 -->

<% @follows.each do |user| %>
  <li>
    <%= link_to gravatar_for(user, size: 50), user %>
    <span class="user"><%= link_to user.name, user %></span><br>
    <span class="user"><%= link_to user.email, user %></span><br>
     <span class="timestamp">
      Posted <%= time_ago_in_words(user.created_at) %> ago.
    </span><br>
  </li>
  
  
<% end %>



<!-- 追加箇所開始 -->
<%= paginate @follows, outer_window: 2 %>
<!-- 追加箇所終了 -->

app/views/users/new.html.erb
<!--<h1>Sign up</h1> -->

<div class="panel panel-default">
  <div class="panel-heading">Sign Up</div>

  <div class="form-horizontal" role="form">
  <%= form_for(@user) do |f| %>
  
      <% if @user.errors.present? %>
        <div class="alert alert-danger">
          <%= alert %>
          <ul>
            <% @user.errors.full_messages.each do |full_message| %>
              <li>
                <%= full_message %>
              </li>
            <% end %> 
          </ul>
        </div>
      <% end %>
      <br>
      <div class="form-group">
          <label for="user_name" class="col-sm-2 control-label">name：</label>
          <div class="col-sm-4">
            <%= f.text_field :name, :class => "form-control", :placeholder => "名前を入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_email" class="col-sm-2 control-label">email：</label>
          <div class="col-sm-4">
            <%= f.text_field :email, :class => "form-control", :placeholder => "メールアドレスを入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_password" class="col-sm-2 control-label">password：</label>
          <div class="col-sm-4">  
            <%= f.password_field :password, :class => "form-control", :placeholder => "パスワードを入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <label for="user_password_confirmation" class="col-sm-2 control-label">Confirmation：</label>
          <div class="col-sm-4">
            <%= f.password_field :password_confirmation, :class => "form-control", :placeholder => "パスワード再度入力してください。" %>
          </div>    
      </div>
      <div class="form-group">
          <div class="col-sm-offset-2 col-sm-2"> 
              <%= f.submit class: "btn btn-sm btn-primary" %> 
          </div>
      </div>
   <% end %>
</div>
</div>

app/views/users/show.html.erb
<!-- 
<%= @user.inspect %>
-->

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <p>
          <%= gravatar_for @user %>
          <%= @user.name %>
        </p>
        
        <p><%= @user.email %></p>
        <P><%= @user.age %></P>
        <p><%= @user.profile_name %></p>
        <p><%= @user.area %></p>
        <p><%= link_to "followings", followings_user_path(@user) %></p>
        <p><%= link_to "followers",  followers_user_path(@user) %></p>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>

    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>\
      </ol>
    <% end %>
  </div>
</div>